# Generated by Django 4.1.3 on 2022-11-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_alter_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(5, 'Best'), (4, 'Good'), (3, 'Not Bad'), (2, 'Soso'), (1, 'Cringe')], default=0),
        ),
    ]
